<a href="https://colab.research.google.com/github/IzaLech/data-scientist-bootcamp/blob/main/01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np
np.__version__

'1.22.4'

In [ ]:
dir(np)

In [ ]:
help(np.array)

Tablica jednowymiarowa: 1D Array

In [5]:
x = np.array([1,5,7,13])
x

array([ 1,  5,  7, 13])

In [6]:
print(x)

[ 1  5  7 13]


In [7]:
type(x)

numpy.ndarray

In [8]:
x.ndim

1

In [9]:
x.shape

(4,)

In [10]:
x.size

4

In [11]:
x.dtype

dtype('int64')

In [12]:
np.array([1.2 , 5.7 , 3.4])

array([1.2, 5.7, 3.4])

In [13]:
y = np.array([1.2 , 5.7 , 3.4])
print(y)

[1.2 5.7 3.4]


In [14]:
y.dtype

dtype('float64')

Tablica dwuwymiarowa: 2D Array

In [15]:
np.array([[1, 2],[-3,7]])


array([[ 1,  2],
       [-3,  7]])

In [16]:
z = np.array([[1, 2],[-3,7]])
print(z)

[[ 1  2]
 [-3  7]]


In [17]:
z.ndim

2

In [18]:
z.shape

(2, 2)

In [19]:
t = np.array([[1, 2, 8],[-3,7,-5]])
print(t)

[[ 1  2  8]
 [-3  7 -5]]


In [20]:
t.ndim

2

In [21]:
t.shape

(2, 3)

Tablica trójwymiarowa: 3D Array