<a href="https://colab.research.google.com/github/IzaLech/data-scientist-bootcamp/blob/main/01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np
np.__version__

'1.22.4'

In [ ]:
dir(np)

In [ ]:
help(np.array)

Tablica jednowymiarowa: 1D Array

In [ ]:
x = np.array([1,5,7,13])
x

array([ 1,  5,  7, 13])

In [ ]:
print(x)

[ 1  5  7 13]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(4,)

In [ ]:
x.size

4

In [ ]:
x.dtype

dtype('int64')

In [ ]:
np.array([1.2 , 5.7 , 3.4])

array([1.2, 5.7, 3.4])

In [ ]:
y = np.array([1.2 , 5.7 , 3.4])
print(y)

[1.2 5.7 3.4]


In [ ]:
y.dtype

dtype('float64')

Tablica dwuwymiarowa: 2D Array

In [ ]:
np.array([[1, 2],[-3,7]])


array([[ 1,  2],
       [-3,  7]])

In [ ]:
z = np.array([[1, 2],[-3,7]])
print(z)

[[ 1  2]
 [-3  7]]


In [ ]:
z.ndim

2

In [ ]:
z.shape

(2, 2)

In [ ]:
t = np.array([[1, 2, 8],[-3,7,-5]])
print(t)

[[ 1  2  8]
 [-3  7 -5]]


In [ ]:
t.ndim

2

In [ ]:
t.shape

(2, 3)

Tablica trójwymiarowa: 3D Array

In [3]:
 u = np.array(
 [[[4,3,1],
  [3,1,2]],
  
  [[4,1,3],
   [4,2,1]]]
 )
 u

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [4]:
u.ndim

3

In [5]:
u.shape

(2, 2, 3)

In [8]:
 h = np.array(
 [[[4,3,1],
  [3,1,2]],
  
  [[4,1,3],
   [4,2,1]],

    [[3,2,1],
   [4,3,2]]]
 )
 h

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [9]:
h.shape

(3, 2, 3)

TYPY DANYCH


In [16]:
A = np.array([3,6,9])
A.dtype

dtype('int64')

In [17]:
A

array([3, 6, 9])

In [12]:
A = np.array([3.7,6.9,9.1])
A.dtype

dtype('float64')

In [18]:
A = np.array([3,6,9], dtype='float')
A.dtype

dtype('float64')

In [19]:
A

array([3., 6., 9.])

In [20]:
A = np.array([3,6,9], dtype='complex')
A.dtype

dtype('complex128')

In [21]:
A

array([3.+0.j, 6.+0.j, 9.+0.j])

In [22]:
A = np.array([3.7,6.9,9.1], dtype='int')
A.dtype

dtype('int64')

In [23]:
A

array([3, 6, 9])

In [25]:
A = np.array([True,False])
A.dtype

dtype('bool')

In [26]:
A = np.array([24,120,230], dtype=np.int8)
A.dtype

dtype('int8')

In [27]:
A

array([ 24, 120, -26], dtype=int8)

In [28]:
A = np.array([24,120,230], dtype=np.uint8)
A.dtype

dtype('uint8')

In [29]:
A

array([ 24, 120, 230], dtype=uint8)

In [30]:
print(A)

[ 24 120 230]
