<a href="https://colab.research.google.com/github/IzaLech/data-scientist-bootcamp/blob/main/02_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Tworzenie tablic

In [2]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [4]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [5]:
np.ones(shape=(5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [6]:
np.ones(shape=(5,7), dtype='int')

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [7]:
np.full(shape=(7,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(start=3, stop=10)

array([3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [19]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [20]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [21]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [23]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [24]:
np.linspace(start=0, stop=1, num=20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [25]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [27]:
# Python sam może dobierać wartość kolumny poprzez wpisanie parametru (-1) - ustawiamy wówczas tylko liczbę wierszy
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [29]:
A.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Podstawowe operacje na tablicach

In [30]:
A = np.array([2,-4,5,8])
B = np.array([1,-7,-3,9])
print(A)
print(B)

[ 2 -4  5  8]
[ 1 -7 -3  9]


In [31]:
A + B

array([  3, -11,   2,  17])

In [40]:
np.add(A,B)

array([  3, -11,   2,  17])

In [32]:
A - B

array([ 1,  3,  8, -1])

In [41]:
np.subtract(A,B)

array([ 1,  3,  8, -1])

In [33]:
A * B

array([  2,  28, -15,  72])

In [42]:
np.multiply(A,B)

array([  2,  28, -15,  72])

In [34]:
A / B

array([ 2.        ,  0.57142857, -1.66666667,  0.88888889])

In [43]:
np.divide(A,B)

array([ 2.        ,  0.57142857, -1.66666667,  0.88888889])

In [35]:
A + 3

array([ 5, -1,  8, 11])

In [44]:
np.add(A,3)

array([ 5, -1,  8, 11])

In [36]:
2 * A

array([ 4, -8, 10, 16])

In [45]:
np.multiply(2,A)

array([ 4, -8, 10, 16])

In [37]:
A * 2

array([ 4, -8, 10, 16])

In [38]:
A + 3*B

array([  5, -25,  -4,  35])

In [49]:
X = np.array([[1,3],[-2,0]])
Y = np.array([[6,0],[-1,2]])
print(X)
print(Y)

[[ 1  3]
 [-2  0]]
[[ 6  0]
 [-1  2]]


In [50]:
X * Y

array([[6, 0],
       [2, 0]])

mnożenie macierzy

In [51]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [52]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [54]:
X @ Y

array([[  3,   6],
       [-12,   0]])

In [53]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

GENEROWANIE LICZB PSEUDOLOSOWYCH

In [56]:
np.random.randn()

0.4336810835823682

In [57]:
np.random.randn()

0.25323917736595963

In [58]:
np.random.randn()

-2.5809294690261257

teraz liczby nie będą wybierane przypadkowo tylko już z góry ustalone kolejne liczby w ustalonej kolejności przez Python

In [59]:
np.random.seed(0)

In [60]:
np.random.randn()

1.764052345967664

In [61]:
np.random.randn()

0.4001572083672233

In [62]:
np.random.randn(10)

array([ 0.97873798,  2.2408932 ,  1.86755799, -0.97727788,  0.95008842,
       -0.15135721, -0.10321885,  0.4105985 ,  0.14404357,  1.45427351])

In [63]:
np.random.randn(10,4)

array([[ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877,  0.15494743,  0.37816252],
       [-0.88778575, -1.98079647, -0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985, -0.38732682, -0.30230275],
       [-1.04855297, -1.42001794, -1.70627019,  1.9507754 ],
       [-0.50965218, -0.4380743 , -1.25279536,  0.77749036],
       [-1.61389785, -0.21274028, -0.89546656,  0.3869025 ]])

In [64]:
np.random.rand()

0.1965823616800535

In [65]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [66]:
np.random.rand(10,2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [67]:
np.random.randint(10)

3

In [68]:
np.random.randint(low=10, high=101)

56

In [69]:
np.random.randint(low=10, high=101, size=10)

array([52, 66, 70, 87, 40, 34, 12, 13, 23, 50])

In [70]:
np.random.choice([3,5,8,1,-2])

3

In [71]:
np.random.choice([3,5,8,1,-2])

1

In [72]:
np.random.choice(['python','java','sql'])

'python'

In [73]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
np.random.shuffle(data)

In [76]:
data

array([1, 0, 5, 2, 9, 7, 4, 6, 8, 3])