<a href="https://colab.research.google.com/github/IzaLech/data-scientist-bootcamp/blob/main/03_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PODSTAWOWE FUNKCJE

In [2]:
import numpy as np
np.exp(1)

2.718281828459045

In [3]:
np.exp(100)

2.6881171418161356e+43

In [4]:
np.sqrt(9)

3.0

In [5]:
np.sqrt(0.64)

0.8

In [12]:
bool(1.5)

True

In [13]:
bool(0)

False

In [6]:
np.all([4,7,-2])

True

In [7]:
np.all([4,0,-2])

False

In [8]:
np.any([4,7,-2])

True

In [9]:
np.any([4,0,-2])

True

In [10]:
np.all([0,0,0])

False

generujemy dowolnych 5 wartości z rozkładu normalnego

In [18]:
A = np.random.randn(5)
A

array([ 0.40569327,  0.54651139, -0.50804364,  0.32258572, -1.11272428])

lub inaczej: teraz będą wartości z przedziału (0 ; 1)

In [19]:
A = np.random.rand(5)
A

array([0.61178585, 0.66972363, 0.35683292, 0.36298295, 0.82904488])

In [21]:
np.argmax(A) #funkcja zwraca indeks z największą wartością

4

In [22]:
A[np.argmax(A)]

0.8290448838106103

In [23]:
np.argmin(A)

2

In [24]:
A[np.argmin(A)]

0.35683291859976374

In [25]:
np.argsort(A) #funkcja sortuje elementy tablicy w kolejności rosnącej po indeksach

array([2, 3, 0, 1, 4])

In [26]:
np.max(A)

0.8290448838106103

In [27]:
np.min(A)

0.35683291859976374

In [28]:
np.mean(A)  #średnia

0.5660740462085698

In [29]:
np.median(A)  #mediana

0.611785854504598

In [30]:
np.std(A)  #odchylenie standardowe

0.1827644984167754

INDEKSOWANIE I WYCINANIE TABLIC

In [33]:
B = np.arange(20)
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# A[index] , A[start:stop] , A[start:] , A[:stop]

In [35]:
B[5]

5

In [36]:
B[5:9]

array([5, 6, 7, 8])

In [37]:
B[11:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [38]:
B[:11]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
B[[1,5,7]]

array([1, 5, 7])

In [41]:
B[-1]

19

In [42]:
B[-2]

18

In [43]:
B = B.reshape(4,5)
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

wycinanie wierszy

In [44]:
B[0]

array([0, 1, 2, 3, 4])

In [45]:
B[1]

array([5, 6, 7, 8, 9])

wycinanie kolumn

In [46]:
B[:,0]

array([ 0,  5, 10, 15])

In [47]:
B[:,1]

array([ 1,  6, 11, 16])

In [48]:
B[:,-1]

array([ 4,  9, 14, 19])

wycinanie elementu

In [49]:
B[0,3]

3

In [50]:
B[1,2]

7

wycinanie fragmentu

In [51]:
B[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [52]:
B[1,2] = 14
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

ITERACJA PO TABLICACH

In [53]:
for row in B:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [54]:
for row in B:
  print(row[0])

0
5
10
15


In [55]:
for row in B:
  print(row[1])

1
6
11
16


In [56]:
for row in B:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [57]:
for item in B.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


ZMIANA ROZMIARU TABLIC

In [59]:
B.shape

(4, 5)

In [60]:
B.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [61]:
B.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [63]:
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [62]:
B.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

MASKI LOGICZNE

In [66]:
C = np.arange(start=-10 , stop=10 , step=0.5)
C = C.reshape(10,-1)
C

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [67]:
C > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [68]:
C[C > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [69]:
# gdy chcemy wyciąć jakiś przedział to poniższa komenda nie zadziała
C[C > -5 and C < 5]

ValueError: ignored

In [70]:
np.bitwise_and(C > -5 , C < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [71]:
C[np.bitwise_and(C > -5 , C < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [73]:
np.bitwise_or(C<-5 , C>5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [74]:
C[np.bitwise_or(C<-5 , C>5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])