<a href="https://colab.research.google.com/github/IzaLech/data-scientist-bootcamp/blob/main/04_numpy_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
# wektor
v1 = np.array([0,4])
v2 = np.array([-1,4])
print(v1)
print(v2)

[0 4]
[-1  4]


NORMA WEKTORA

In [2]:
# norma wektora 
np.linalg.norm(v1)

4.0

In [5]:
np.linalg.norm(v2)

4.123105625617661

In [7]:
# to samo w przestrzeni R^n dla n=3
v3 = np.array([-10,10,13])
np.linalg.norm(v3)

19.209372712298546

ODLEGŁOŚC PUNKTÓW



In [9]:
# na płaszczyźnie
p = np.array([0,3])
q = np.array([4,0])
np.linalg.norm(p - q)

5.0

In [10]:
# w przestrzeni R^n
p = np.array([0,3,1])
q = np.array([4,0,2])
np.linalg.norm(p - q)

5.0990195135927845

---

MNOŻENIE MACIERZY

! liczba kolumn w lewej macierzy musi być równa liczbie wierszy w prawej macierzy !

mnożenie macierzy nie jest przemienne

wynikiem jest macierz o liczbie wierszy 1. macierzy i liczbie kolumn drugiej macierzy

In [13]:
# Przykład 1
X = np.array([[5,3],[3,9]])
Y = np.array([[1],[-1]])
print(X , '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [14]:
Z = np.dot(X,Y)
Z

array([[ 2],
       [-6]])

In [15]:
Z.shape

(2, 1)

In [16]:
# Przykład 2
X = np.array([[2,-1,3],[3,1,0]])
Y = np.array([[2,1,-1],[0,-1,2],[3,2,0]])
print(X , '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [18]:
Z = np.dot(X,Y)
Z

array([[13,  9, -4],
       [ 6,  2, -1]])

WYZNACZNIK MACIERZY

tylko dla macierzy kwadratowej

In [19]:
A = np.array([[2,4],[-1,3]])
np.linalg.det(A)

9.999999999999998

In [21]:
# możemy zaokrąglić tę watość
round(np.linalg.det(A))

10

In [22]:
B = np.array([[2,4,0],[0,-1,3],[1,1,1]])
np.linalg.det(B)

4.0

In [23]:
B

array([[ 2,  4,  0],
       [ 0, -1,  3],
       [ 1,  1,  1]])

---
ŚLAD MACIERZY

czyli suma elementów na przekątnej

In [24]:
A = np.array([[2,4],[-1,3]])
np.trace(A)

5

---
MACIERZ JEDNOSTKOWA (I)

na przekątnej są 1, reszta to 0

In [26]:
np.eye(5 , dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [27]:
np.eye(3 , dtype='float')

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
# typ danych 'float' jest domyślny:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

---
MACIERZ ODWROTNA

Macierz kwadratowa A posiada macierz odwrotną (macierz B) gdy: A*B = B*A = I

In [30]:
A

array([[ 2,  4],
       [-1,  3]])

In [32]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [39]:
# sprawdzenie
np.dot(A,B)


array([[1.00000000e+00, 0.00000000e+00],
       [2.77555756e-17, 1.00000000e+00]])

In [40]:
# by pominąć tak dokładny zapis matematyczny ustawiamy:
np.set_printoptions(precision=4 , suppress=True)
np.dot(A,B)

array([[1., 0.],
       [0., 1.]])

In [41]:
np.dot(B,A)

array([[ 1., -0.],
       [ 0.,  1.]])

---
MACIERZ TRANSPONOWANA

In [43]:
A

array([[ 2,  4],
       [-1,  3]])

In [42]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [47]:
A.T

array([[ 2, -1],
       [ 4,  3]])

In [45]:
Z = np.array([[2,4,0],[0,-1,3],[1,-5,8]])
Z

array([[ 2,  4,  0],
       [ 0, -1,  3],
       [ 1, -5,  8]])

In [46]:
np.transpose(Z)

array([[ 2,  0,  1],
       [ 4, -1, -5],
       [ 0,  3,  8]])

In [48]:
Z.T

array([[ 2,  0,  1],
       [ 4, -1, -5],
       [ 0,  3,  8]])

---
ROZWIĄZYWANIE UKŁADÓW RÓWNAŃ


In [53]:
A = np.array([[2,4],[1,-1]])
X = np.array([['x_1'],['x_2']])
B = np.array([[10],[-1]])
print(A, '\n')
print(X, '\n')
print(B)
# A*X = B

[[ 2  4]
 [ 1 -1]] 

[['x_1']
 ['x_2']] 

[[10]
 [-1]]


In [55]:
A_1 = np.linalg.inv(A)
A_1

array([[ 0.1667,  0.6667],
       [ 0.1667, -0.3333]])

In [56]:
np.dot(A_1 , B)

array([[1.],
       [2.]])