<a href="https://colab.research.google.com/github/IzaLech/data-scientist-bootcamp/blob/main/05_numpy_funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 13.00, 11.70, 12.20, 2000],
                  [12.20, 13.40, 12.20, 13.20, 1500]])
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


SUMA

In [ ]:
# funkcja sum() - suma wszystkich elementów
price.sum()

4650.1

In [ ]:
np.sum(price)

4650.1

In [ ]:
# zliczanie sum w kolumnach
price.sum(axis=0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [ ]:
np.sum(price, axis=0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [ ]:
# sumowanie w wierszach
price.sum(axis=1)

array([1049.7, 2049.4, 1551. ])

In [ ]:
np.sum(price, axis=1)

array([1049.7, 2049.4, 1551. ])

MINIMUM

In [ ]:
np.min(price)

11.7

In [ ]:
np.min(price , axis = 0)

array([  12.2,   12.8,   11.7,   12.2, 1000. ])

In [ ]:
np.min(price , axis = 1)

array([11.9, 11.7, 12.2])

MAXIMUM

In [ ]:
np.max(price)

2000.0

MEDIANA

In [ ]:
np.median(price)

12.6

ŚREDNIA

In [ ]:
np.mean(price)

310.0066666666667

In [ ]:
np.mean(price , axis=0)

array([  12.36666667,   13.06666667,   11.93333333,   12.66666667,
       1500.        ])

ODCHYLENIE STANDARDOWE

In [ ]:
  np.std(price)

622.3781502877133

In [ ]:
np.std(price , axis=0)

array([1.24721913e-01, 2.49443826e-01, 2.05480467e-01, 4.10960934e-01,
       4.08248290e+02])

WARIANCJA

In [ ]:
  np.var(price , axis=0)

array([1.55555556e-02, 6.22222222e-02, 4.22222222e-02, 1.68888889e-01,
       1.66666667e+05])

In [ ]:
np.set_printoptions(precision=4 , suppress=True)
np.var(price , axis=0)

array([     0.0156,      0.0622,      0.0422,      0.1689, 166666.6667])