<a href="https://colab.research.google.com/github/IzaLech/data-scientist-bootcamp/blob/%C4%86wiczenia_NUMPY/NUMPY_%C4%87wiczenia_071_080_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 71](#1)
* [Ćwiczenie 72](#2)
* [Ćwiczenie 73](#3)
* [Ćwiczenie 74](#4)
* [Ćwiczenie 75](#5)
* [Ćwiczenie 76](#6)
* [Ćwiczenie 77](#7)
* [Ćwiczenie 78](#8)
* [Ćwiczenie 79](#9)
* [Ćwiczenie 80](#10)

### <a name='0'></a>Import biblioteki

In [2]:
import numpy as np

np.random.seed(42)
np.__version__

'1.22.4'

### <a name='1'></a> Ćwiczenie 71
Podana jest poniższa tablica $A$:

```
A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])
```
Od drugiego wiersza tablicy $A$ przestaw losowo wiersze w tablicy.

__Wskazówka:__ Użyj funkcji _np.random.shuffle()_.


In [ ]:
A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])
np.random.shuffle(A[1:])
A

array([['id', 'price'],
       ['005', '1.49'],
       ['001', '14.99'],
       ['004', '2.49'],
       ['003', '7.99'],
       ['002', '4.99']], dtype='<U32')

### <a name='2'></a> Ćwiczenie 72
Podana jest poniższa tablica $A$:

```
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])
```
Zwróć tablicę indeksów, które posortują tablicę $A$ rosnąco.

__Oczekiwny wynik:__


```
array([5, 2, 1, 0, 4, 3])
```
__Wskazówka:__ Użyj funkcji _np.argsort()_.



In [ ]:
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])
np.argsort(A)

array([5, 2, 1, 0, 4, 3])

### <a name='3'></a> Ćwiczenie 73
Podana jest poniższa tablica $A$:

```
A = np.random.randn(10, 8)
```

Zaokrąglij wartości tej tablicy do trzeciego miejsca po przecinku.

__Wskazówka:__ Użyj funkcji _np.round()_.

In [ ]:
A = np.random.randn(10, 8)
A

array([[-1.41859646,  0.19033698,  0.13575383,  0.60808966,  0.70498131,
         0.36092338, -1.46696789,  0.89262947],
       [-0.10525713, -0.95534644, -0.41476463, -1.39874088, -0.34408054,
         0.75078589, -0.32762518, -0.86159805],
       [-0.2581848 ,  0.46095562, -1.34938997, -1.01907279,  0.12701224,
        -1.24944372,  1.94511561, -0.15333646],
       [-0.90698723, -0.81735416, -0.48312268, -0.56982835, -2.09159967,
         1.26374053, -0.01548334, -0.02737645],
       [ 0.81787351, -1.05460447, -0.75832712,  0.45741565, -0.06437805,
         0.34490234, -0.08008734, -0.24138013],
       [ 1.43351549,  1.06579371, -2.49875914,  1.48032856,  2.15872852,
         1.23177838, -0.21432448, -0.68919421],
       [ 0.72783311, -0.61906936,  0.35615983, -0.02188087,  1.21805044,
        -0.38945802, -0.44280234,  0.37822661],
       [ 1.9338398 ,  0.08097081, -0.41645636,  0.85750325,  0.71812828,
        -0.95147175, -0.5361601 ,  1.09652886],
       [ 0.42801284, -2.46969887

In [ ]:
np.round(A, 3) # lub ładniej np.round(A, decimals=3)

array([[-1.419,  0.19 ,  0.136,  0.608,  0.705,  0.361, -1.467,  0.893],
       [-0.105, -0.955, -0.415, -1.399, -0.344,  0.751, -0.328, -0.862],
       [-0.258,  0.461, -1.349, -1.019,  0.127, -1.249,  1.945, -0.153],
       [-0.907, -0.817, -0.483, -0.57 , -2.092,  1.264, -0.015, -0.027],
       [ 0.818, -1.055, -0.758,  0.457, -0.064,  0.345, -0.08 , -0.241],
       [ 1.434,  1.066, -2.499,  1.48 ,  2.159,  1.232, -0.214, -0.689],
       [ 0.728, -0.619,  0.356, -0.022,  1.218, -0.389, -0.443,  0.378],
       [ 1.934,  0.081, -0.416,  0.858,  0.718, -0.951, -0.536,  1.097],
       [ 0.428, -2.47 ,  0.482,  0.926, -0.838,  0.677,  1.872,  0.396],
       [-0.626, -0.522,  0.013,  0.378,  0.063,  0.502, -0.147,  0.181]])

### <a name='4'></a> Ćwiczenie 74
Wyznacz pierwiastki wielomianu:
* $W(x) = 4x^2 + 5x + 1$


__Wskazówka:__ Użyj funkcji _np.roots()_ oraz _np.polyval()_.

In [ ]:
W = np.array([4,5,1])
np.roots(W)

array([-1.  , -0.25])

Dokonaj sprawdzenia.

In [ ]:
np.polyval(W, -1)

0

In [ ]:
np.polyval(W, -0.25)

0.0

### <a name='5'></a> Ćwiczenie 75
Wyznacz pierwiastki wielomianów:
* $Q(x) = 2x^3 + 4x^2 -5x + 1$
* $R(x) = 2x^3 -5x + 1$

__Wskazówka:__ Użyj funkcji _np.roots()_.

In [ ]:
Q = np.array([2, 4, -5, 1])
np.roots(Q)

array([-2.91610583,  0.65388685,  0.26221898])

In [ ]:
R = np.array([2, 0, -5, 1])
np.roots(R)

array([-1.67298165,  1.46961743,  0.20336421])

### <a name='6'></a> Ćwiczenie 76
Podane są wielomiany:

* $W(x) = 4x^2 + 5x + 1$
* $Q(x) = 2x^3 + 4x^2 -5x + 1$


In [ ]:
W = np.array([4, 5, 1])
Q = np.array([2, 4, -5, 1])

Wykonaj działania:
* $W(x) + Q(x)$

In [ ]:
np.polyadd(W,Q)

array([2, 8, 0, 2])

* $W(x) - Q(x)$


In [ ]:
np.polysub(W, Q)

array([-2,  0, 10,  0])

* $W(x) * Q(x)$


In [ ]:
np.polymul(W,Q)

array([  8,  26,   2, -17,   0,   1])

* $W(x) + 2Q(x)$

In [ ]:
np.polyadd(W,2*Q)

array([ 4, 12, -5,  3])

### <a name='7'></a> Ćwiczenie 77
Podana jest poniższa tablica:

```
A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])
```

Użyj funkcji znaku (_sign function_) dla tablicy $A$. Dla przypomnienia funkcja działa nastpująco: dla wartości ujemnych zwraca -1, dla zera wartość zero, dla wartości dodatnich 1.

__Oczekiwany wynik:__


```
array([[-1,  1,  0,  1, -1],
       [ 1, -1, -1,  1,  1]])
```
__Wskazówka:__ Użyj funkcji _np.sign()_.


In [4]:
A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])

np.sign(A)

array([[-1,  1,  0,  1, -1],
       [ 1, -1, -1,  1,  1]])

### <a name='8'></a> Ćwiczenie 78
Wykorzystując funkcję _np.arange()_ wygeneruj poniższą tablicę:


```
array(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
       '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
       '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
       '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
       '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
       '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
       '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
       '2021-01-29', '2021-01-30', '2021-01-31'], dtype='datetime64[D]')
```



In [12]:
np.arange(start='2021-01-01' , stop='2021-02-01' , step=1,  dtype='datetime64[D]')

array(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
       '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
       '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
       '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
       '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
       '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
       '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
       '2021-01-29', '2021-01-30', '2021-01-31'], dtype='datetime64[D]')


### <a name='9'></a> Ćwiczenie 79

Wykorzystując funkcję _np.arange()_ wygeneruj poniższą tablicę:



```
array([['2021-01', '2021-02', '2021-03'],
       ['2021-04', '2021-05', '2021-06'],
       ['2021-07', '2021-08', '2021-09'],
       ['2021-10', '2021-11', '2021-12']], dtype='datetime64[M]')
```



In [15]:
A = np.arange('2021-01' , stop='2022-01' , dtype='datetime64[M]')
A = A.reshape(4,3)
A

array([['2021-01', '2021-02', '2021-03'],
       ['2021-04', '2021-05', '2021-06'],
       ['2021-07', '2021-08', '2021-09'],
       ['2021-10', '2021-11', '2021-12']], dtype='datetime64[M]')

### <a name='10'></a> Ćwiczenie 80

Wykorzystując funkcję _np.datetime64()_ wygeneruj dzisiejszą datę (datę w chwili robienia ćwiczenia).

In [17]:
np.datetime64('now')

numpy.datetime64('2023-06-01T14:41:24')

In [18]:
np.datetime64('today')

numpy.datetime64('2023-06-01')